* Unit test
    | test case                                  | result             | success/all | comment                                |
    |--------------------------------------------+--------------------+-------------+----------------------------------------|
    | ParallelSnapshotReaderTest.java            | 9/6                |             |                                        |
    | SourceInfoTest.java                        | 38/2               |             | Whether it's need to test for GTID set |
    | ZZZGtidSetIT.java                          | X                  |             | To fix                                 |
    |--------------------------------------------+--------------------+-------------+----------------------------------------|
    | BinlogReaderBufferIT.java                  | O                  |             |                                        |
    | ConnectionIT.java                          | O                  |             |                                        |
    | MetadataIT.java                            | O                  |             |                                        |
    | MySqlAntlrDdlParserTest.java               | O                  |             |                                        |
    | MySqlDdlParserTest.java                    | O                  |             |                                        |
    | MySqlDateTimeInKeyIT.java                  | O                  |             |                                        |
    | MySqlDecimalColumnIT.java                  | O                  |             |                                        |
    | MysqlDefaultValueAllZeroTimeIT.java        | O                  |             |                                        |
    | MysqlDefaultValueIT.java                   | O                  |             |                                        |
    | MySqlEnumColumnIT.java                     | O                  |             |                                        |
    | MySqlFixedLengthBinaryColumnIT.java        | O                  |             |                                        |
    | MySqlNumericColumnIT.java                  | O                  |             |                                        |
    | MySqlTimestampColumnIT.java                | O                  |             |                                        |
    | MySqlUnsignedIntegerIT.java                | O                  |             |                                        |
    | MySqlYearIT.java                           | O                  |             |                                        |
    | MySqlSchemaTest.java                       | O                  | 5/5         |                                        |
    | MySqlSourceTypeInSchemaIT.java             | O                  | 1/1         |                                        |
    | MySqlTableMaintenanceStatementsIT.java     | O                  | 1/1         |                                        |
    | MySqlValueConvertersTest.java              | O                  | 4/4         | Removed JSON test                      |
    | TopicNameSanitizationIT.java               | O                  |             |                                        |
    | BinlogReaderIT.java                        | O                  | 10/10       |                                        |
    | MySqlGeometryIT.java                       | O                  | 2/2         |                                        |
    |--------------------------------------------+--------------------+-------------+----------------------------------------|
    | ChainedReaderTest.java                     | O                  |             |                                        |
    | FiltersTest.java                           | O                  |             |                                        |
    | MySqlConnectorIT.java                      | O                  |             |                                        |
    | MySqlConnectorRegressionIT.java            | O                  |             |                                        |
    | MySqlConnectorTest.java                    | O                  |             |                                        |
    | MySqlUnsignedIntegerConverterTest.java     | O                  |             |                                        |
    | MySqlGeometryTest.java                     | O                  |             |                                        |
    | ReconcilingBinlogReaderTest.java           | O                  |             |                                        |
    | MysqlDefaultValueTest.java                 | O                  | 16/16       | ->AbstractMysqlDefaultValueTest.java   |
    | MysqlAntlrDefaultValueTest.java            | O                  | 19/19       | ->AbstractMysqlDefaultValueTest.java   |
    | ReadBinLogIT.java                          | O                  | 6/6         |                                        |
    | SnapshotReaderIT.java                      | O                  | 8/8         |                                        |
    |--------------------------------------------+--------------------+-------------+----------------------------------------|
    | AbstractMySqlConnectorOutputTest.java.2fix | -                  |             |                                        |
    | MySqlTaskContextIT.java.2fix               | -                  |             |                                        |
    | MySqlTaskContextTest.java.2fix             | -                  |             |                                        |
    |--------------------------------------------+--------------------+-------------+----------------------------------------|
    | MySqlConnectorJsonIT.java                  | Not test           |             | No need to test json                   |
    | DatabaseDifferences.java                   | Not test           |             | Interface                              |
    | junit/SkipForLegacyParser.java             | Not test           |             | Interface                              |
    | junit/SkipTestForLegacyParser.java         | Not test           |             | Tool                                   |
    | MySQLConnection.java                       | Not test           |             | Tool                                   |
    | UniqueDatabase.java                        | Not test           |             |                                        |
    | TableConvertersTest.java                   | junit=> to convert |             | Not yet implemented                    |
    | Configurator.java                          | Not test           |             |                                        |
    | AbstractMysqlDefaultValueTest.java         | Not test           |             |                                        |


** TODO AbstractMysqlDefaultValueTest.java
The abstract class how to test
** BinlogReaderBufferIT.java
  - DDL \\
    The DDL is fetched from test/resource folder
  - Database connection String
    The DB connection info is fetched from system properties.
  - shouldCorrectlyManageRollback
    Problem: All the rollback transaction appeared in the record different from the expectation. \\
    MySql's BEGIN statement  is contained in the QUERY EVENT. In the original source code, the begin transaction is \\
at the QUERY event. Please find the below source code to find it(9.5 final)
    + debezium-connect-mysql->EventBuffer.java->add
    + debezium-connect-mysql->BinlogReader.java->handleQueryEvent
    + mysql-binlog-connector-java->BinaryLogClient->updateGtid
    All these logical have to be moved to the MARIA_GTID_EVENT event as one new transaction. Please find the coressponding \\
source code for the improvement.
  - shouldProcessLargeTransaction
    Problem: Only 3 insert statement appeared in the result different from the expectation of 40
    One parameter called [BUFFER_SIZE_FOR_BINLOG_READER] impact the capacity of the event buffer. This config parameter \\
is used in the debezium-connect-mysql->BinlogReader.java
    #+BEGIN_SRC
      public BinlogReader(String name, MySqlTaskContext context, HaltingPredicate acceptAndContinue, long serverId) {
      ....
      client.registerEventListener(context.bufferSizeForBinlogReader() == 0
          ? this::handleEvent
          : (new EventBuffer(context.bufferSizeForBinlogReader(), this))::add);
    #+END_SRC
    At the same time, in the EventBuffer, it should be switched to switchToBufferFullMode.
** BinlogReaderIT
*** shouldHandleTimestampTimezones
  Have to set the UniqueDatabase's TIMEZONE same to mariadb's time_zone. And one more important difference is that \\
the decimal exceed the definition is truncated rather than round. At the same time, the decimal is only supported 3 \\
digits rather than 6.
*** shouldCreateSnapshotOfSingleDatabase
  Warning message "New transaction started but the previous was not completed, processing the buffer" \\
and "Commit requested but TX was not started before". To resolve the warning message, add the [consumeEvent(event);]
to the else in the mysql-binlog-connector-java->EventBuffer->Add. Mariadb's QUERY event only contain those DDL, commit
and ROLLBACK. Thos queries (insert/delte/update) are in the (WRITE_ROWS/UPDATE_ROWS/DELETE_ROWS).
*** shouldAcceptTls12
**** Set the ssl for mariadb
  - Create the CA certificate
    #+BEGIN_SRC
$cd yomo-connector/yomo-connector-maria/src/test/resources/ssl
$openssl genrsa 2048 > ca-key.pem

$ openssl req -new -x509 -nodes -days 365000 -key ca-key.pem -out ca-cert.pem
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [XX]:JP
State or Province Name (full name) []:Tokyo
Locality Name (eg, city) [Default City]:Tokyo
Organization Name (eg, company) [Default Company Ltd]:None
Organizational Unit Name (eg, section) []:Data
Common Name (eg, your name or your server's hostname) []:mdbNode01
Email Address []:mdbNode01@gmail.com
    #+END_SRC
  - Create the server certificate
    #+BEGIN_SRC
$ openssl req -newkey rsa:2048 -days 365000 -nodes -keyout server-key.pem -out server-req.pem
Generating a 2048 bit RSA private key
...............................+++
.....+++
writing new private key to 'server-key.pem'
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [XX]:JP
State or Province Name (full name) []:Tokyo
Locality Name (eg, city) [Default City]:Tokyo
Organization Name (eg, company) [Default Company Ltd]:None
Organizational Unit Name (eg, section) []:Data]
Common Name (eg, your name or your server's hostname) []:mdbNode01
Email Address []:mdbNode01@sbibits.com

Please enter the following 'extra' attributes
to be sent with your certificate request
A challenge password []:
An optional company name []:
$ openssl rsa -in server-key.pem -out server-key.pem
writing RSA key
$ls
ca-cert.pem  ca-key.pem  server-key.pem  server-req.pem
$ openssl x509 -req -in server-req.pem -days 365000 -CA ca-cert.pem -CAkey ca-key.pem -set_serial 01 -out server-cert.p
em
Signature ok
subject=/C=JP/ST=Tokyo/L=Tokyo/O=None/OU=Data/CN=mdbNode01/emailAddress=mdbNode01@gmail.com
Getting CA Private Key
$ ls
ca-cert.pem  ca-key.pem  server-cert.pem  server-key.pem  server-req.pem
    #+END_SRC
  - Create the client certificate
    #+BEGIN_SRC
$ openssl req -newkey rsa:2048 -days 365000 -nodes -keyout client-key.pem -out client-req.pem
Generating a 2048 bit RSA private key
........................................................................................+++
.....................................+++
writing new private key to 'client-key.pem'
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [XX]:JP
State or Province Name (full name) []:Tokyo
Locality Name (eg, city) [Default City]:Tokyo
Organization Name (eg, company) [Default Company Ltd]:None
Organizational Unit Name (eg, section) []:Data
Common Name (eg, your name or your server's hostname) []:mdbNode01
Email Address []:mdbNode01@gmail.com

Please enter the following 'extra' attributes
to be sent with your certificate request
A challenge password []:
An optional company name []:
$ openssl rsa -in client-key.pem -out client-key.pem
writing RSA key


$ openssl x509 -req -in client-req.pem -days 365000 -CA ca-cert.pem -CAkey ca-key.pem -set_serial 01 -out client-cert.p
em
Signature ok
subject=/C=JP/ST=Tokyo/L=Tokyo/O=None/OU=Data/CN=mdbNode01/emailAddress=mdbNode01@gmail.com
Getting CA Private Key
    #+END_SRC
  - Verify the certificates
    #+BEGIN_SRC
$ openssl verify -CAfile ca-cert.pem server-cert.pem client-cert.pem
server-cert.pem: C = JP, ST = Tokyo, L = Tokyo, O = BITS, OU = Data Consulting, CN = mdbNode01, emailAddress = mdbNode01@sbibits.com
error 18 at 0 depth lookup:self signed certificate
OK
client-cert.pem: OK
    #+END_SRC


** MySqlDateTimeInKey
  - The event is as below
    | Seq | EventType     |       GTID | Query           | SNAPSHORT | Addition                 | num |
    |-----+---------------+------------+-----------------+-----------+--------------------------+-----|
    |     | SET           |          - |                 | yes       | SET character_set_server | 1   |
    |     | USE           |          - |                 | yes       | USE database name        | 1   |
    |   1 | Query         | 2-223344-1 | CREATE DATABASE | yes       | DROP DATABASE            | 2   |
    |   2 | Query         | 2-223344-2 | CREATE TABLE    | yes       | DROP TABLE               | 2   |
    |   3 | Annotate_rows | 2-223344-3 | INSERT INTO     |           |                          |     |
    |   4 | Annotate_rows | 2-223344-4 | INSERT INTO     |           |                          |     |

** MySqlDefaultValueIT
*** generatedValueTest
mariadb does not support [generated] with not null option. The value is mandatory.
#+BEGIN_SRC
CREATE TABLE GENERATED_TABLE (
  A SMALLINT UNSIGNED,
  B SMALLINT UNSIGNED AS (2 * A),
  C SMALLINT UNSIGNED AS (3 * A) NOT NULL
);

#+END_SRC
*** columnTypeAndDefaultValueChange
  binlog_rows_query_log_events does not support on the mariadb
** ReadBinLogIT
  - Add wait into recordedEventData
    The CDC is async process. So there is lapse from data inserted into db to be caught in the CDC. In the test, \\
sometimes could not find the rows because of this lapse. What I did is to add wait logical util finding the row \\
match the expectation. Of course, adding the timeout if there is really no data in the CDC.
  - Event sequence
    The event sequence is different from the mysql. Two insert query within one transaction will generate below events.
      | Seq | Event      | Comment |
      |-----+------------+---------|
      |   1 | MARIA_GTID | Begin   |
      |   2 | TABLE_MAP  |         |
      |   3 | WRITE_ROW  |         |
      |   4 | TABLE_MAP  |         |
      |   5 | WRITE_ROW  |         |
      |   6 | XID        | Commit  |
      |-----+------------+---------|
  - Disable shouldFailToConnectToInvalidBinlogFile
    In the maria version, I only use GTID as the replication. The binlog file and position are only used for reference.
